sSTR[999]=0;sCON[999]=0;sDEX[999]=0;sQUI[999]=0;sINT[999]=0;sPIE[999]=0;sEMP[999]=0;sCHA[999]=0; 
sSTR[998]=0;sCON[998]=0;sDEX[998]=0;sQUI[998]=0;sINT[998]=0;sPIE[998]=0;sEMP[998]=0;sCHA[998]=0; 
sSTR[1]=60;sCON[1]=60;sDEX[1]=60;sQUI[1]=60;sINT[1]=60;sPIE[1]=60;sEMP[1]=60;sCHA[1]=60; 
sSTR[2]=40;sCON[2]=40;sDEX[2]=75;sQUI[2]=75;sINT[2]=70;sPIE[2]=60;sEMP[2]=60;sCHA[2]=60; 
sSTR[3]=90;sCON[3]=60;sDEX[3]=40;sQUI[3]=40;sINT[3]=60;sPIE[3]=60;sEMP[3]=70;sCHA[3]=60; 
sSTR[16]=60;sCON[16]=80;sDEX[16]=50;sQUI[16]=50;sINT[16]=60;sPIE[16]=60;sEMP[16]=60;sCHA[16]=60; 

Abilities = new Array(24)		
Abilities[1]=new abilityPT("Staff",0,83,5,0,0,0)
Abilities[2]=new abilityPT("Cloth Armor",0,99,7,0,0,0)
Abilities[3]=new abilityPT("Leather Armor",0,100,7,0,0,0)
Abilities[4]=new abilityPT("Shields (Small)",0,102,7,0,0,0)
Abilities[5]=new abilityPT("Evade I",0,113,4,0,0,0)
Abilities[6]=new abilityPT("Blunt",0,122,5,1,0,0)
Abilities[7]=new abilityPT("Blades",0,123,5,1,0,0)
Abilities[8]=new abilityPT("Reinforced Armor",0,124,7,0,0,0)
Abilities[9]=new abilityPT("Piercing",0,125,5,1,0,0)
Abilities[10]=new abilityPT("Parry",2,107,4,1,0,0)
Abilities[11]=new abilityPT("Shields",5,97,5,1,0,0)
Abilities[12]=new abilityPT("Shields (Medium)",5,103,7,0,0,0)
Abilities[13]=new abilityPT("Celtic Dual",5,147,5,1,0,0)
Abilities[14]=new abilityPT("Short Bows",10,117,5,0,0,0)
Abilities[15]=new abilityPT("Protect I",15,109,4,0,0,0)
Abilities[16]=new abilityPT("Evade II",15,114,4,0,0,0)
Abilities[17]=new abilityPT("Intercept",19,110,4,0,0,0)
Abilities[18]=new abilityPT("Triple Wield",20,162,4,0,0,0)
Abilities[19]=new abilityPT("Protect II",23,111,4,0,0,0)
Abilities[20]=new abilityPT("Evade III",25,115,4,0,0,0)
Abilities[21]=new abilityPT("Flurry",30,174,4,0,0,0)
Abilities[22]=new abilityPT("Protect III",32,112,4,0,0,0)
Abilities[23]=new abilityPT("Advanced Evade",35,173,4,0,0,0)
Abilities[24]=new abilityPT("Charge",40,196,0,0,0,0)
	
//Styles = new Array(70);
//Styles[1]=new stylePT(123,"Shining Blade",2,"","High","Starter","","","","",0,"")
//Styles[2]=new stylePT(123,"Return Blade",4,"Slowed","Low","Medium","Medium Bonus","","","You parry",0,"Decreases the target\'s combat speed.  Duration 20 seconds")
//Styles[3]=new stylePT(123,"Taunting Blade",6,"Taunt","Medium","Low","Medium Bonus","","Medium&nbsp;Penalty","",0,"")
//Styles[4]=new stylePT(123,"Enervating Blade",8,"Detaunt","Medium","","","Medium&nbsp;Bonus","","",0,"")
//Styles[5]=new stylePT(123,"Glowing Blade",10,"Hindered","Medium","Medium","Medium Bonus","","","To side of target",0,"Reduces the target\'s movement speed.  Value 100% Duration 14 seconds")
//Styles[6]=new stylePT(123,"Lunging Blade",12,"Bleeding","Medium","Medium","Medium Bonus","Low&nbsp;Bonus","","[*] Return Blade",0,"Does damage to a target over a period of time.  Damage per tick (every 4 seconds) 5 Damage type Body Duration 30 seconds")
//Styles[7]=new stylePT(123,"Auroric Blade",15,"Slowed","Low","Medium","Medium Bonus","","","[*] Glowing Blade",0,"Decreases the target\'s combat speed.  Duration 20 seconds")
//Styles[8]=new stylePT(123,"Fire Blade",18,"","High","Medium","Low Bonus","","Low&nbsp;Penalty","",0,"")
//Styles[9]=new stylePT(123,"Horizon Blade",21,"Stunned","Low","High","Medium Bonus","Low&nbsp;Bonus","","You block",0,"Stuns the target for a brief period of time.  Duration 4 seconds")
//Styles[10]=new stylePT(123,"Kinetic Blade",25,"","Medium","High","Medium Bonus","","","[*] Lunging Blade",0,"")
//Styles[11]=new stylePT(123,"Dancing Blade",29,"Bleeding","Low","Medium","High Bonus","","","[*] Horizon Blade",0,"Does damage to a target over a period of time.  Damage per tick (every 4 seconds) 8 Damage type Body Duration 40 seconds")
//Styles[12]=new stylePT(123,"Revenging Blade",34,"","Medium","Medium","Medium Bonus","","Medium&nbsp;Penalty","Behind target",0,"")
//Styles[13]=new stylePT(123,"Spectrum Blade",39,"Slowed","Medium","Medium","Low Bonus","Medium&nbsp;Bonus","","[*] Fire Blade",0,"Decreases the target\'s combat speed.  Duration 20 seconds")
//Styles[14]=new stylePT(123,"Prismatic Blade",44,"","Low","High","Medium Bonus","","","[*] Dancing Blade",0,"")
//Styles[15]=new stylePT(123,"Brilliant Blade",50,"","Medium","High","Very High Bonus","","","[*] Revenging Blade",0,"")
//Styles[16]=new stylePT(122,"Contusions",2,"","High","Starter","","","","",0,"")
//Styles[17]=new stylePT(122,"Bruiser",4,"Stunned","Low","Medium","Medium Bonus","","","You block",0,"Stuns the target for a brief period of time.  Duration 2 seconds")
//Styles[18]=new stylePT(122,"Blunt Trauma",6,"Detaunt","Medium","","","Medium&nbsp;Bonus","","",0,"")
//Styles[19]=new stylePT(122,"Slam",8,"Taunt","Medium","Low","Medium Bonus","","Medium&nbsp;Penalty","",0,"")
//Styles[20]=new stylePT(122,"Side Bash",10,"Slowed","Medium","Medium","Low Bonus","","","To side of target",0,"Decreases the target\'s combat speed.  Duration 20 seconds")
//Styles[21]=new stylePT(122,"Impact",12,"Bleeding","Low","Medium","Medium Bonus","","Low&nbsp;Penalty","[*] Bruiser",0,"Does damage to a target over a period of time.  Damage per tick (every 4 seconds) 4 Damage type Body Duration 25 seconds")
//Styles[22]=new stylePT(122,"Windfall",15,"Slowed","Low","Medium","High Bonus","Low&nbsp;Bonus","","[*] Impact",0,"Decreases the target\'s combat speed.  Duration 20 seconds")
//Styles[23]=new stylePT(122,"Force of Might",18,"","High","Medium","Low Bonus","","","",0,"")
//Styles[24]=new stylePT(122,"Unstoppable Force",21,"Hindered","Medium","Medium","Medium Bonus","Low&nbsp;Bonus","","[*] Side Bash",0,"Reduces the target\'s movement speed.  Value 100% Duration 19 seconds")
//Styles[25]=new stylePT(122,"Back Crush",25,"","Medium","High","Medium Bonus","Medium&nbsp;Bonus","","Behind target",0,"")
//Styles[26]=new stylePT(122,"Bone Crusher",29,"Bleeding","Low","Medium","Medium Bonus","Low&nbsp;Bonus","","[*] Windfall",0,"Does damage to a target over a period of time.  Damage per tick (every 4 seconds) 7 Damage type Body Duration 40 seconds")
//Styles[27]=new stylePT(122,"Mauler",34,"No","Medium","High","Medium Bonus","Medium&nbsp;Bonus","","[*] Unstoppable Force",0,"")
//Styles[28]=new stylePT(122,"Stunning Blow",39,"Slowed","Low","Medium","Medium Bonus","Low&nbsp;Bonus","","You parry",0,"Decreases the target\'s combat speed.  Duration 20 seconds")
//Styles[29]=new stylePT(122,"Crushing Blow",44,"","Medium","Medium","Very High Bonus","Low&nbsp;Bonus","","[*] Back Crush",0,"")
//Styles[30]=new stylePT(122,"Devastating Blow",50,"Stunned","Medium","Medium","Medium Bonus","","","[*] Stunning Blow",0,"Stuns the target for a brief period of time.  Duration 10 seconds")
//Styles[31]=new stylePT(147,"Misty Gloom",2,"","High","Starter","","","","",0,"")
//Styles[32]=new stylePT(147,"Blinding Rain",4,"Bleeding","Low","Medium","Medium Bonus","","","You evade",0,"Does damage to a target over a period of time.  Damage per tick (every 4 seconds) 3 Damage type Body Duration 20 seconds")
//Styles[33]=new stylePT(147,"Squall",6,"Taunt","Medium","Low","Low Bonus","","Medium&nbsp;Penalty","",0,"")
//Styles[34]=new stylePT(147,"Snow Shower",8,"Hindered","Medium","High","Medium Bonus","","","Behind target",0,"Reduces the target\'s movement speed.  Value 100% Duration 12 seconds")
//Styles[35]=new stylePT(147,"Gale",10,"Bleeding","Low","Medium","Medium Bonus","","Low&nbsp;Penalty","[*] Snow Shower",0,"Does damage to a target over a period of time.  Damage per tick (every 4 seconds) 5 Damage type Body Duration 30 seconds")
//Styles[36]=new stylePT(147,"Blizzard",12,"Slowed","Low","High","Medium Bonus","","","[*] Blinding Rain",0,"Decreases the target\'s combat speed.  Duration 20 seconds")
//Styles[37]=new stylePT(147,"Thunderstorm",15,"Detaunt","Low","Medium","Medium Bonus","High&nbsp;Bonus","","[*] Snow Shower",0,"")
//Styles[38]=new stylePT(147,"Ice Storm",18,"Stunned","Medium","High","Medium Bonus","","","To side of target",0,"Stuns the target for a brief period of time.  Duration 4 seconds")
//Styles[39]=new stylePT(147,"Hurricane",21,"","High","Medium","Low Bonus","","Medium&nbsp;Penalty","",0,"")
//Styles[40]=new stylePT(147,"Tornado",25,"Hindered","Low","Medium","High Bonus","Medium&nbsp;Bonus","","You parry",0,"Reduces the target\'s movement speed.  Value 100% Duration 23 seconds")
//Styles[41]=new stylePT(147,"Tempest",29,"Bleeding","Medium","High","Medium Bonus","","","[*] Ice Storm",0,"Does damage to a target over a period of time.  Damage per tick (every 4 seconds) 15 Damage type Body Duration 40 seconds")
//Styles[42]=new stylePT(147,"Meteor Shower",34,"","Low","Medium","Medium Bonus","","","[*] Tornado",0,"")
//Styles[43]=new stylePT(147,"Solar Flare",39,"","Medium","High","Low Bonus","Low&nbsp;Bonus","","[*] Hurricane",0,"")
//Styles[44]=new stylePT(147,"Twin Star",44,"Bleeding","Medium","Medium","Medium Bonus","","","[*] Meteor Shower",0,"Does damage to a target over a period of time.  Damage per tick (every 4 seconds) 25 Damage type Body Duration 40 seconds")
//Styles[45]=new stylePT(147,"Supernova",50,"Slowed","Medium","High","High Bonus","Low&nbsp;Bonus","","[*] Tempest",0,"Decreases the target\'s combat speed.  Duration 20 seconds")
//Styles[46]=new stylePT(125,"Dragonfly",2,"","High","Starter","","","","",0,"")
//Styles[47]=new stylePT(125,"Wasp's Sting",4,"Bleeding","Low","Medium","Medium Bonus","","","Behind target",0,"Does damage to a target over a period of time.  Damage per tick (every 4 seconds) 3 Damage type Body Duration 20 seconds")
//Styles[48]=new stylePT(125,"Bumblebee's Sting",6,"Taunt","Medium","Low","Medium Bonus","","High&nbsp;Penalty","",0,"")
//Styles[49]=new stylePT(125,"Hornet's Sting",8,"Slowed","Medium","Medium","Medium Bonus","","","[*] Wasp's Sting",0,"Decreases the target\'s combat speed.  Duration 20 seconds")
//Styles[50]=new stylePT(125,"Scorpion",10,"Detaunt","Medium","","","Medium&nbsp;Bonus","","",0,"")
//Styles[51]=new stylePT(125,"Black Widow",12,"","High","Medium","Low Bonus","","Low&nbsp;Penalty","",0,"")
//Styles[52]=new stylePT(125,"Tarantula",15,"Bleeding","Low","Medium","Medium Bonus","Low&nbsp;Bonus","","You block",0,"Does damage to a target over a period of time.  Damage per tick (every 4 seconds) 6 Damage type Body Duration 35 seconds")
//Styles[53]=new stylePT(125,"Sidewinder",18,"","Medium","High","Medium Bonus","","","[*] Black Widow",0,"")
//Styles[54]=new stylePT(125,"Copperhead",21,"Hindered","Medium","Medium","Medium Bonus","","Low&nbsp;Penalty","To side of target",0,"Reduces the target\'s movement speed.  Value 100% Duration 15 seconds")
//Styles[55]=new stylePT(125,"Diamondback",25,"Stunned","Low","Medium","Medium Bonus","Medium&nbsp;Bonus","","You evade",0,"Stuns the target for a brief period of time.  Duration 5 seconds")
//Styles[56]=new stylePT(125,"Viper's Bite",29,"","Medium","High","Medium Bonus","Medium&nbsp;Bonus","","[*] Tarantula",0,"")
//Styles[57]=new stylePT(125,"Asp's Bite",34,"Slowed","Low","Medium","Very High Bonus","Medium&nbsp;Bonus","","[*] Sidewinder",0,"Decreases the target\'s combat speed.  Duration 20 seconds")
//Styles[58]=new stylePT(125,"Cobra's Bite",39,"","Low","High","High Bonus","Low&nbsp;Bonus","","[*] Copperhead",0,"")
//Styles[59]=new stylePT(125,"Dragonspider",44,"Bleeding","Medium","Medium","Medium Bonus","","","[*] Diamondback",0,"Does damage to a target over a period of time.  Damage per tick (every 4 seconds) 10 Damage type Body Duration 40 seconds")
//Styles[60]=new stylePT(125,"Wyvern's Bite",50,"Bleeding","Medium","High","High Bonus","Low&nbsp;Bonus","","[*] Dragonspider",0,"Does damage to a target over a period of time.  Damage per tick (every 4 seconds) 11 Damage type Body Duration 40 seconds")
//Styles[61]=new stylePT(97,"Numb",3,"Stunned","High","High","","","","",0,"Stuns the target for a brief period of time.  Duration 2 seconds")
//Styles[62]=new stylePT(97,"Stun",8,"Stunned","High","High","","","","You block",0,"Stuns the target for a brief period of time.  Duration 3 seconds")
//Styles[63]=new stylePT(97,"Disable",13,"Stunned","High","High","","","","To side of target",0,"Stuns the target for a brief period of time.  Duration 4 seconds")
//Styles[64]=new stylePT(97,"Incapacitate",18,"Stunned","Very High","High","","Medium&nbsp;Bonus","","You block",0,"Stuns the target for a brief period of time.  Duration 5 seconds")
//Styles[65]=new stylePT(97,"Paralyze",23,"Stunned","High","High","","","","Behind target",0,"Stuns the target for a brief period of time.  Duration 6 seconds")
//Styles[66]=new stylePT(97,"Bash",29,"Stunned","High","Medium","","","","You block",0,"Stuns the target for a brief period of time.  Duration 7 seconds")
//Styles[67]=new stylePT(97,"Mangle",35,"Stunned","High","Medium","","","","To side of target",0,"Stuns the target for a brief period of time.  Duration 8 seconds")
//Styles[68]=new stylePT(97,"Slam",42,"Stunned","Very High","Medium","","","","",0,"Stuns the target for a brief period of time.  Duration 9 seconds")
//Styles[69]=new stylePT(97,"Brutalize",50,"Stunned","Medium","Medium","","","","You block",0,"Stuns the target for a brief period of time.  Duration 10 seconds")

Spells = new Array(0)

Lines = new Array(0);
